### ISSUE TITLE
Pure CSS stylesheets not found / classes not recognized

### ISSUE THREAD

**Issue by lkraav** [philipwalton/html-inspector#44]
"The class 'pure-u-1-3' is used in the HTML but not found in any stylesheet." <div class="pure-u-1-3">

But the grid works and everything is fine on the page. Loading HTML Inspector 0.8.0 from cdnjs.

Demo https://c9.io/lkraav/html-inspector-pure-css/workspace/hello-world.html

**Comment by erikwoods** [comment]
It is unfortunate that we have to write exceptions for attribute selectors. :( I have many.
