### ISSUE TITLE
"PhantomJS must be installed to use the HTML Inspector CLI." (Windows 8.1)

### ISSUE THREAD

**Issue by yuricamara** [philipwalton/html-inspector#50]
Hi guys,

I followed the steps below:

1. Downloaded phantomjs.
2. Extracted the files to c:/bin/phantomjs/
3. Put this path in Windows Environment Variable.
4. Restart the machine.
5. Ran phantomjs --version in command line and the result was 1.9.8 as expected.
6. Ran htmlinspector index.html in a folder with this file and the message "PhantomJS must be installed to use the HTML Inspector CLI." appeared in console.

Who could help me, please?

**Comment by philipwalton** [comment]
Hmmm, this may be a Windows/Unix compatibility issue. Out of curiousity, what does running `which phantomjs` return from the command line?

I ask because here's the logic that produces the error you're seeing:
https://github.com/philipwalton/html-inspector/blob/0.8.1/bin/html-inspector#L32-L35

**Comment by yuricamara** [comment]
Windows doesn´t recognize the *which* command.

**Comment by philipwalton** [comment]
Thanks, should be fixed as of [0.8.2](https://github.com/philipwalton/html-inspector/releases/tag/0.8.2). Let me know if you're still having problems.

**Comment by yuricamara** [comment]
Thank you very much @philipwalton .

It works like a charm!
