### ISSUE TITLE
"The span element cannot be a child of the del element." 

### ISSUE THREAD

**Issue by evilebottnawi** [philipwalton/html-inspector#58]
@philipwalton This is not true, https://developer.mozilla.org/ru/docs/Web/HTML/Element/del#Examples

**Comment by evilebottnawi** [comment]
@philipwalton repo is not maintenance?

**Comment by philipwalton** [comment]
@evilebottnawi please be patient, if you'd like to submit a patch to fix this error, feel free, otherwise realize that it may take some time for me to get to it.

**Comment by evilebottnawi** [comment]
@philipwalton thanks for answer, when I have time, and if there is no patch, I'll do it
